### ISSUE TITLE
IndexedDB support with PubSub/Live Updates

### ISSUE THREAD

**Issue by pcfreak30** [ipfs/helia-ipns#20]
I am developing with Helia in the browser and things work, but the thing that gets a hit/misses the most at the moment is IPNS lookups.

I would like to see 2 things:

- Storing the IPNS entries to an IndexedDB cache, with the block store or data store, with an expiration time.
- When you have cached entries, have a means of live updating to be able to refresh the newer entry in the background.

I will work on this in the future if required but would be nice to have it done upstream.

Kudos!

**Comment by achingbrain** [comment]
Sounds like an oversight - once resolved we should cache the record in the local datastore at the end of the [#findIpnsRecord](https://github.com/ipfs/helia-ipns/blob/main/packages/ipns/src/index.ts#L286-L309) method
