### ISSUE TITLE
Connect Helia Node with Infura Gateway

### ISSUE THREAD

**Issue by seanrasku** [ipfs/helia-ipns#56]
Looking through the docs, I see the only way to instantiate a Helia node is with createHelia(), which takes a libp2p. Is it possible to connect it to an Infura IPFS gateway yet? I'm trying to understand how to pin data with Helia IPNS, but cannot find documentation to answer my question.

**Comment by achingbrain** [comment]
If the Infura IPFS gateway is running an IPFS node on a multiaddr you know, you can either dial the multiaddr after startup:

```js
import { createHelia } from 'helia'

const helia = await createHelia()
helia.libp2p.dial(multiaddr)
```

or you can configure libp2p to bootstrap to the Infura node (e.g. connect on startup):

```js
import { createHelia } from 'helia'
import { bootstrap } from '@libp2p/bootstrap'

const helia = await createHelia({
  libp2p: {
    peerDiscovery: [
      bootstrap({
        list: [
          multiaddr,
          // ...other bootstrap nodes
        ]
      })
    ]
  }
})
```

See the [default libp2p config](https://github.com/ipfs/helia/blob/main/packages/helia/src/utils/libp2p-defaults.ts#L44) and the [default list of bootstrap nodes](https://github.com/ipfs/helia/blob/main/packages/helia/src/utils/bootstrappers.ts)

**Comment by TJKoury** [comment]
This still doesn't seem to be working, maybe it just doesn't work in the browser yet.  

Here's a [test sandbox](https://codesandbox.io/p/sandbox/helia-connectivity-demo-forked-hrr2yx?file=%2Fnode_modules%2F%40helia%2Funixfs%2Fdist%2Fsrc%2Findex.d.ts%3A1%2C1), using the same instance / transport as the helia instance that seems to be working on the page.

**Comment by SgtPooki** [comment]
@TJKoury the browser usecase is not likely to succeed well yet. Follow https://github.com/ipfs/helia/issues/182 for more details

**Comment by achingbrain** [comment]
Tracked in https://github.com/ipfs/helia/issues/182
